"use client"
import type { Metadata } from "next";

import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import logo from './assets/images/logo.svg';
import logo_mini from './assets/images/logo-mini.svg';
import PrivateRoute from "@/components/PrivateRoute";
import { useRouter } from "next/navigation";
import Image from 'next/image';
import { MdOutlineNotificationsNone } from "react-icons/md"
import { MdFullscreen } from "react-icons/md";
import { MdPowerSettingsNew } from "react-icons/md";
import { MdMenu } from "react-icons/md";
import Link from "next/link";
import { useState, useEffect } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const router = useRouter();
  const [userData, setUserData] = useState<any>(null);

  useEffect(() => {
    // Carrega os dados do usuário do localStorage
    const userDataFromStorage = localStorage.getItem('userData');
    if (userDataFromStorage) {
      setUserData(JSON.parse(userDataFromStorage));
    }
  }, []);

  const hasAccessToModule = (module: string): boolean => {
    if (!userData || !userData.setor) return false;
    
    // Admin tem acesso a tudo
    if (userData.setor === 'Admin') return true;
    
    // Mapear módulos por setor
    const moduleAccess: { [key: string]: string[] } = {
      'Compras': ['Compras'],
      'Oficina': ['Oficina'],
      'Estoque': ['Estoque'],
      'Expedição': ['Expedição'],
      'Expedicao': ['Expedição'], // Variação de escrita
    };
    
    const userModules = moduleAccess[userData.setor] || [];
    return userModules.includes(module);
  };

  function deslogar() {
          localStorage.setItem('auth', 'false');

      router.push('/login'); // redireciona
  }
  return (
    <PrivateRoute>
      <div className="min-h-screen bg-gray-100 flex flex-col">
        {/* NAVBAR */}
        <nav className="w-full flex items-center justify-between fixed top-0 left-0 bg-white shadow px-6 z-50 h-16">
          <div className="flex items-center gap-4">
            <a href="index.html"  className="hidden lg:block">
              <Image src={logo.src} alt="logo" className="h-10" width={200} height={64} />
            </a>
            <a href="index.html" className="block lg:hidden">
              <Image src={logo_mini.src} alt="logo-mini" className="h-8" width={64} height={64} />
            </a>
            {userData && (
              <div className="hidden md:block">
                <span className="text-gray-700 font-medium">
                  Olá, {userData.usuario?.split(' ')[0] || 'Usuário'}!
                </span>
              </div>
            )}
          </div>
          <div className="flex items-center gap-3">
            <button className="p-2 hover:bg-gray-100 rounded transition">
              <MdFullscreen className="text-xl text-black" />
            </button>
            <ul className="flex items-center gap-2">
              <li>
                <button className="p-2 hover:bg-gray-100 rounded transition hidden lg:block">
                  <MdOutlineNotificationsNone className="text-xl text-black" />
                </button>
              </li>
              <li className="relative">
                <button className="p-2 hover:bg-gray-100 rounded transition relative lg:hidden">
                  <MdOutlineNotificationsNone className="text-xl text-black" />
                  <span className="absolute top-0 right-0 block w-2 h-2 bg-red-600 rounded-full"></span>
                </button>
                {/* Dropdown de notificações (simples, não funcional) */}
                {/* Adicione lógica com useState para mostrar/esconder */}
                {/* <div className="absolute right-0 mt-2 w-80 bg-white rounded-lg shadow-lg py-3 z-40">
                  ...
                </div> */}
              </li>
              <li>
                <button className="p-2 hover:bg-gray-100 rounded transition hidden lg:block">
                  <MdPowerSettingsNew className="text-xl text-black" onClick={deslogar} />
                </button>
              </li>
            </ul>
            <button className="p-2 hover:bg-gray-100 rounded transition lg:hidden">
              <MdMenu className="text-xl text-black" />
            </button>
          </div>
        </nav>

        <div className="flex pt-16">
          {/* SIDEBAR */}
          <aside className="w-64 min-h-screen bg-white border-r shadow flex flex-col">
            <ul className="flex flex-col gap-2 mt-4">
              <li>
                <a
                  href="index.html"
                  className="flex items-center px-4 py-2 text-gray-700 hover:bg-blue-50 rounded transition"
                >
                  {/* <i className="mdi mdi-home mr-3 text-xl"></i> */}
                  {/* <span className="font-medium">Dashboard</span> */}
                </a>
              </li>
              {/* Compras */}
              {hasAccessToModule('Compras') && (
              <li>
                <details className="group">
                  <summary className="flex items-center px-4 py-2 cursor-pointer text-gray-700 hover:bg-blue-50 rounded transition">
                    <i className="fa fa-shopping-cart mr-3 text-xl"></i>
                    <span className="font-medium">Compras</span>
                    <svg
                      className="ml-auto transition-transform group-open:rotate-90 w-4 h-4"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path d="M9 5l7 7-7 7" />
                    </svg>
                  </summary>
                  <ul className="ml-10 mt-1 flex flex-col gap-1">
                    <li>
                     <details className="group">
                        <summary className="flex items-center px-4 py-2 cursor-pointer pl-2 text-gray-700 hover:bg-blue-50 rounded transition">
                          {/* <i className="fa fa-shopping-cart mr-3 text-xl"></i> */}
                          <span className="font-medium">Cotação</span>
                          <svg
                            className="ml-auto transition-transform group-open:rotate-90 w-4 h-4"
                            fill="none"
                            stroke="currentColor"
                            viewBox="0 0 24 24"
                          >
                            <path d="M9 5l7 7-7 7" />
                          </svg>
                        </summary>
                        <ul className="ml-10 mt-1 flex flex-col gap-1">
                          <li>
                          <Link href="/compras/cotacao" className="text-gray-600 py-1 px-2 rounded hover:bg-blue-100">
                            Criar Cotação
                          </Link>
                          </li>
                          <li>
                          <Link href="/compras/cotacao/comparativo" className="text-gray-600 py-1 px-2 rounded hover:bg-blue-100">
                            Comparativo
                          </Link>
                          </li>
                          <li>
                          <Link href="/compras/cotacao/pedido" className="text-gray-600 py-1 px-2 rounded hover:bg-blue-100">
                            Pedido
                          </Link>
                          </li>
                        </ul>
                      </details>
                    </li>
                    <li>
                     <Link href="/compras/kanban" className="text-gray-600 py-1 px-2 rounded hover:bg-blue-100">
                      Kanban
                    </Link>
                    </li>
                    {/* <li>
                     <Link href="/compras/cotacao/pedido" className="text-gray-600 py-1 px-2 rounded hover:bg-blue-100">
                      3
                    </Link>
                    </li> */}
                  </ul>
                </details>
              </li>
              )}
              {/* Oficina */}
              {hasAccessToModule('Oficina') && (
              <li>
                <details className="group">
                  <summary className="flex items-center px-4 py-2 cursor-pointer text-gray-700 hover:bg-blue-50 rounded transition">
                    <i className="fa fa-shopping-cart mr-3 text-xl"></i>
                    <span className="font-medium">Oficina</span>
                    <svg
                      className="ml-auto transition-transform group-open:rotate-90 w-4 h-4"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path d="M9 5l7 7-7 7" />
                    </svg>
                  </summary>
                  <ul className="ml-10 mt-1 flex flex-col gap-1">
                    <li>
                     <Link href="/oficina/checkList" className="text-gray-600 py-1 px-2 rounded hover:bg-blue-100">
                      Check List
                    </Link>
                    </li>
                  </ul>
                </details>
              </li>
              )}
               {hasAccessToModule('Estoque') && (
               <li>
                <details className="group">
                  <summary className="flex items-center px-4 py-2 cursor-pointer text-gray-700 hover:bg-blue-50 rounded transition">
                    <i className="fa fa-shopping-cart mr-3 text-xl"></i>
                    <span className="font-medium">Estoque</span>
                    <svg
                      className="ml-auto transition-transform group-open:rotate-90 w-4 h-4"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path d="M9 5l7 7-7 7" />
                    </svg>
                  </summary>
                  <ul className="ml-10 mt-1 flex flex-col gap-1">
                    <li>
                     <Link href="/estoque/contagem" className="text-gray-600 py-1 px-2 rounded hover:bg-blue-100">
                      Contagem
                    </Link>
                    </li>
                  </ul>
                </details>
              </li>
              )}
              {hasAccessToModule('Expedição') && (
              <li>
                <details className="group">
                  <summary className="flex items-center px-4 py-2 cursor-pointer text-gray-700 hover:bg-blue-50 rounded transition">
                    <i className="fa fa-shopping-cart mr-3 text-xl"></i>
                    <span className="font-medium">Expedição</span>
                    <svg
                      className="ml-auto transition-transform group-open:rotate-90 w-4 h-4"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path d="M9 5l7 7-7 7" />
                    </svg>
                  </summary>
                  <ul className="ml-10 mt-1 flex flex-col gap-1">
                    <li>
                     <Link href="/expedicao/entregas" className="text-gray-600 py-1 px-2 rounded hover:bg-blue-100">
                      Entregas
                    </Link>
                    </li>
                  </ul>
                </details>
              </li>
              )}
              {/* Sistema - Admin tem acesso sempre */}
              {userData?.setor === 'Admin' && (
              <li>
                <details className="group">
                  <summary className="flex items-center px-4 py-2 cursor-pointer text-gray-700 hover:bg-blue-50 rounded transition">
                    <i className="fa fa-gear mr-3 text-xl"></i>
                    <span className="font-medium">Sistema</span>
                    <svg
                      className="ml-auto transition-transform group-open:rotate-90 w-4 h-4"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path d="M9 5l7 7-7 7" />
                    </svg>
                  </summary>
                  <ul className="ml-10 mt-1 flex flex-col gap-1">
                    <li>
                     <Link href="/usuario" className="text-gray-600 py-1 px-2 rounded hover:bg-blue-100">
                      Usuários
                    </Link>
                    </li>
                  </ul>
                </details>
              </li>
              )}
            </ul>
          </aside>

          <main style={{flex: 1, padding: "32px"}}>
            {children}
          </main>


        </div>
      </div>
    </PrivateRoute>
  );
}
